<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CredentialTable extends Doctrine_Table
{

    /**
     * create new instance of CredentialTable
     * @return object CredentialTable
     */
    public static function instance()
    {
        return Doctrine::getTable('Credential');
    }

    /**
     * Function loads all credentials
     * @param string $orderby, orderby String if needed, optional parameter.
     * @return Doctrine_Collection
     */
    public function getAllCredentials($orderby = '')
    {
        $query = Doctrine_Query::create()
                        ->from('Credential c');
        if ($orderby != '') {
            $query->orderby($orderby);
        }
        return $query->execute();
    }

    /**
     * Function loads all usermodules
     *
     * @param String $orderby, orderby if needed, optional paramter
     * @return Doctrine Collection
     */
    public function getAllUserModule($orderby = '')
    {
        $query = Doctrine_Query::create()
                        ->select('DISTINCT c.user_module as user_module')
                        ->from('Credential c');

        if ($orderby != '') {
            $query->orderby($orderby);
        }

        return $query->execute();
    }

    /**
     * Function saves the order of the Modules
     *
     * @param array $order, items to save
     * @param int $position, set position
     * @return true
     */
    public function saveOrderOfModules(array $order, $position)
    {
        foreach ($order as $item) {
            $module = Doctrine_Query::create()
                            ->update('Credential c')
                            ->set('c.user_module_position', '?', $position++)
                            ->where('c.user_module = ?', $item)
                            ->execute();
        }
        return true;
    }

    /**
     * get all credential by Id
     * 
     * @param int $id, id of group to load
     * @param string $orderby, orderby string
     * @return Doctrine_Collection
     */
    public function getAllGroups($id, $orderby = '')
    {
        $query = Doctrine_Query::create()
                        ->from('Credential c')
                        ->where('c.user_module = ?', $id)
                        ->andWhere('c.user_right = ?', 'showModule');
        if ($orderby != '') {
            $query->orderby($orderby);
        }
        return $query->execute();
    }

    /**
     * Save the order of an group
     *
     * @param array $data, data
     * @param int $position, position
     * @return true;
     */
    public function saveOrderOfGroups(array $data, $position)
    {
        $order = $data['grid'];
        foreach ($order as $item) {
            $module = Doctrine_Query::create()
                            ->update('Credential c')
                            ->set('c.user_group_position', '?', $position++)
                            ->where('c.user_module = ?', $data['module'])
                            ->andWhere('c.user_group = ?', $item)
                            ->execute();
        }
        return true;
    }

    public function getCredentialIdByRight($group, $module, $right)
    {
        return Doctrine_Query::create()
                ->from('Credential c')
                ->where('c.user_module = ?', $group)
                ->andWhere('c.user_group = ?', $module)
                ->andWhere('c.user_right = ?', $right)
                ->execute();
    }

}