<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CredentialTable extends Doctrine_Table {

    
    /**
     * create new instance of CredentialTable
     * @return object CredentialTable
     */
    public static function instance() {
       return Doctrine::getTable('Credential');
    }

    /**
     * Function loads all credentials
     * @param string $orderby, orderby String if needed, optional parameter.
     * @return Doctrine_Collection
     */
    public function getAllCredentials($orderby = '') {
        $query = Doctrine_Query::create()
            ->select('c.*')
            ->from('Credential c');
        if($orderby != '') {
            $query->orderby($orderby);
        }
        return $query->execute();
    }

    /**
     * Function loads all usermodules
     *
     * @param String $orderby, orderby if needed, optional paramter
     * @return Doctrine Collection
     */
    public function getAllUsermodule($orderby = '') {
        $query = Doctrine_Query::create()
            ->select('DISTINCT c.usermodule as usermodule')
            ->from('Credential c');
        
        if($orderby != '') {
            $query->orderby($orderby);
        }
           
        return $query->execute();
    }

    /**
     * Function saves the order of the Modules
     *
     * @param array $order, items to save
     * @param int $position, set position
     * @return true
     */
    public function saveOrderOfModules(array $order, $position) {
        foreach($order as $item) {
            $module = Doctrine_Query::create()
                ->update('Credential c')
                ->set('c.usermoduleposition','?',$position++)
                ->where('c.usermodule = ?', $item)
                ->execute();
        }
        return true;
    }

    /**
     * get all credential by Id
     * 
     * @param int $id, id of group to load
     * @param string $orderby, orderby string
     * @return Doctrine_Collection
     */
    public function getAllGroups($id, $orderby = '') {
        $query = Doctrine_Query::create()
            ->select('c.*')
            ->from('Credential c')
            ->where('c.usermodule = ?', $id)
            ->andWhere('c.userright = ?', 'showModule');
        if($orderby != '') {
            $query->orderby($orderby);
        }
        return $query->execute();
    }

    /**
     * Save the order of an group
     *
     * @param array $data, data
     * @param int $position, position
     * @return true;
     */
    public function saveOrderOfGroups(array $data, $position) {
        $order = $data['grid'];
        foreach($order as $item) {
            $module = Doctrine_Query::create()
                ->update('Credential c')
                ->set('c.usergroupposition','?',$position++)
                ->where('c.usermodule = ?', $data['module'])
                ->andWhere('c.usergroup = ?', $item)
                ->execute();
        }
        return true;
    }


    public function getCredentialIdByRight($group, $module, $right) {
        return Doctrine_Query::create()
            ->select('c.*')
            ->from('Credential c')
            ->where('c.usermodule = ?', $group)
            ->andWhere('c.usergroup = ?', $module)
            ->andWhere('c.userright = ?', $right)
            ->execute();
        
    }


}