<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumenttemplateSlotTable extends Doctrine_Table {

        /**
     * create new instance of FormTemplate
     * @return object FormTemplate
     */
    public static function instance() {
        return Doctrine::getTable('DocumenttemplateSlot');
    }


    /**
     * Get all Slots by Template id
     * @param int $id
     * @return Doctrine_Collection
     */
    public function getSlotByDocumentTemplateId($id) {
        return Doctrine_Query::create()
            ->select('dts.*')
            ->from('DocumenttemplateSlot dts')
            ->where('dts.documenttemplateversion_id = ?', $id)
            ->orderBy('dts.position asc')
            ->execute();
    }

    /**
     * Get Slot by its id
     * @param int $slot_id, slotid
     * @return Doctrine_Collection
     */
    public function getSlotById($slot_id) {
        return Doctrine_Query::create()
            ->select('dts.*')
            ->from('DocumenttemplateSlot dts')
            ->where('dts.id = ?', $slot_id)
            ->execute();
    }


    public function getSlotByWorkflowSlotId($workflowslot_id) {
        return Doctrine_Query::create()
            ->select('dts.*')
            ->from('DocumenttemplateSlot dts')
            ->leftJoin('dts.WorkflowSlot wfs')
            ->where('wfs.id = ?', $workflowslot_id)
            ->execute();
        

    }

}