<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentTemplateVersionTable extends Doctrine_Table {


     /**
     * create new instance of FormTemplate
     * @return object FormTemplate
     */
    public static function instance() {
        return Doctrine::getTable('DocumentTemplateVersion');
    }

    /**
     * Set template inactive
     * @param int $id
     * @return true
     */
    public function setTemplateInactiveById($id) {
        Doctrine_Query::create()
            ->update('DocumentTemplateVersion dtv')
            ->set('dtv.active_version','?',0)
            ->where('dtv.id = ?', $id)
            ->execute();
        return true;
    }


    /**
     * Set template inactive
     * @param int $id
     * @return true
     */
    public function setTemplateActiveById($id) {
        Doctrine_Query::create()
            ->update('DocumentTemplateVersion dtv')
            ->set('dtv.active_version','?',1)
            ->where('dtv.id = ?', $id)
            ->execute();
        return true;
    }

    /**
     * Set all templates inactive
     * @param int $id
     * @return true
     */
    public function setAllTemplateInactiveByTemplateId($id) {
        Doctrine_Query::create()
            ->update('DocumentTemplateVersion dtv')
            ->set('dtv.active_version','?',0)
            ->where('dtv.document_template_id = ?', $id)
            ->execute();
        return true;
    }
    /**
     *
     * @param int $id, id of the template
     * @return Doctrine_Collection
     */
    public function getDocumentTemplateId($id) {
        return Doctrine_Query::create()
            ->select('dtv.document_template_id, dtv.version')
            ->from('DocumentTemplateVersion dtv')
            ->where('dtv.id = ?', $id)
            ->execute();
    }


    /**
     * Load all Versions to a Documenttemplate by its parent id
     * @param int $id, id of parent element
     * @return Doctrine_Collection
     */
    public function getAllVersionByTemplateId($id) {
        return Doctrine_Query::create()
            ->from('DocumentTemplateVersion dtv')
            ->where('dtv.document_template_id = ?', $id)
            ->orderBy('dtv.created_at DESC')
            ->execute();
    }

    /**
     * Get Active Version of an template by id
     *
     * @param int $id, documenttemplate id
     * @return Doctrine_Collection
     */
    public function getActiveVersionById($id) {
        return Doctrine_Query::create()
            ->select('dtv.*')
            ->from('DocumentTemplateVersion dtv')
            ->where('dtv.document_template_id = ?', $id)
            ->andWhere('dtv.active_version = ?', 1)
            ->execute();
    }


    /**
     * get a documenttemplateversion by its id
     *
     * @param <type> $id
     * @return Doctrine_Collection
     */
    public function getVersionById($id) {
        return Doctrine_Query::create()
            ->from('DocumentTemplateVersion dtv')
            ->where('dtv.id = ?', $id)
            ->execute();
    }


}