<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailConfigurationTable extends Doctrine_Table {
    /**
     * create new instance of EmailConfigurationTable
     * @return object EmailConfigurationTable
     */
    public static function instance() {
        return Doctrine::getTable('EmailConfiguration');
    }


    /**
     * Loads email config
     * @return Doctrine_Collection
     */
    public function getEmailConfiguration() {
        return Doctrine_Query::create()
                ->from('EmailConfiguration ec')
                ->execute();
    }

    /**
     * Update Email configuration
     * @param array $data
     * @return true
     */
    public function updateEmailConfiguration(array $data) {
       Doctrine_Query::create()
            ->update('EmailConfiguration ec')
            ->set('ec.system_reply_address', '?', $data['emailtab_systemreplyaddress'])
            ->set('ec.active_type', '?', $data['emailtab_emailtype'])
            ->set('ec.smtp_host', '?', $data['email_smtp_server'])
            ->set('ec.smtp_port', '?', $data['email_smtp_port'])
            ->set('ec.smtp_username', '?', $data['email_smtp_username'])
            ->set('ec.smtp_password', '?', $data['email_smtp_password'])
            ->set('ec.smtp_encryption', '?', $data['emailtab_encryption'])
            //->set('ec.smtpuseauth', '?', $data['email_smtp_auth'])
            ->set('ec.send_mailpath', '?', $data['email_sendmail'])
	    ->set('allow_email_transport','?', $data['email_allowsendingemails'] )
            ->where('ec.id = ?',1)
            ->execute();
        return true;
    }

}