<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailConfigurationTable extends Doctrine_Table {
    /**
     * create new instance of EmailConfigurationTable
     * @return object EmailConfigurationTable
     */
    public static function instance() {
        return Doctrine::getTable('EmailConfiguration');
    }


    /**
     * Loads email config
     * @return Doctrine_Collection
     */
    public function getEmailConfiguration() {
        return Doctrine_Query::create()
                ->select('ec.*')
                ->from('EmailConfiguration ec')
                ->execute();
    }

    /**
     * Update Email configuration
     * @param array $data
     * @return true
     */
    public function updateEmailConfiguration(array $data) {
       Doctrine_Query::create()
            ->update('EmailConfiguration ec')
            ->set('ec.systemreplyaddress', '?', $data['emailtab_systemreplyaddress'])
            ->set('ec.activetype', '?', $data['emailtab_emailtype'])
            ->set('ec.smtphost', '?', $data['email_smtp_server'])
            ->set('ec.smtpport', '?', $data['email_smtp_port'])
            ->set('ec.smtpusername', '?', $data['email_smtp_username'])
            ->set('ec.smtppassword', '?', $data['email_smtp_password'])
            ->set('ec.smtpencryption', '?', $data['emailtab_encryption'])
            //->set('ec.smtpuseauth', '?', $data['email_smtp_auth'])
            ->set('ec.sendmailpath', '?', $data['email_sendmail'])
	    ->set('allowemailtransport','?', $data['email_allowsendingemails'] )
            ->where('ec.id = ?',1)
            ->execute();
        return true;
    }

}