<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FieldTable extends Doctrine_Table {

    
    /**
     *
     * create new instance of FieldTable
     * @return object FieldTable
     */
    public static function instance() {
        return Doctrine::getTable('Field');
    }

    /**
     * Load all records
     * @return Doctrine_Collection
     */
    public function getAllFields() {
        return Doctrine_Query::create()
            ->from('Field f')
            ->select('f.*')
            ->orderBy('f.id DESC')
            ->where('f.deleted_at IS NULL')
            ->execute();
    }
    /**
     *
     * @param int $id, id of record to delete
     * @return true
     */
    public function deleteField($id) {
        Doctrine_Query::create()
            ->update('Field f')
            ->set('f.deleted_at','?',time())
            ->where('f.id = ?',$id)
            ->execute();
        return true;
    }

    /**
     * Get field by id
     * @param int $id, id of the field
     * @return Doctrine_Collection
     */
    public function getFieldById($id) {
        return Doctrine_Query::create()
            ->from('Field f')
            ->select('f.*')
            ->where('f.deleted_at IS NULL')
            ->andWhere('f.id = ?', $id)
            ->execute();
    }

    /**
     *
     * @param int $id, id of field to update
     * @param array $data, data to update
     * @return true
     */
    public function updateFieldById($id, $data) {
        Doctrine_Query::create()
            ->update('Field f')
            ->set('f.color','?', $data['createFileWindow_color'])
            ->set('f.writeprotected','?',$data['createFileWindow_writeprotected'])
            ->set('f.title','?',$data['createFileWindow_fieldname'])
            ->where('f.id = ?',$id)
            ->execute();
        return true;
    }


}