<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FieldComboboxTable extends Doctrine_Table {

    /**
     * create new instance of FieldComboboxTable
     * @return object FieldComboboxTable
     */
    public static function instance() {
       return Doctrine::getTable('FieldCombobox');
    }


    /**
     * Find all groups for a parent field
     * @param int $id, id of the parent field
     * @return Doctrine_Collection
     */
    public function findComboboxByFieldId($id) {
        return Doctrine_Query::create()
            ->from('FieldCombobox fcb')
            ->select('fcb.*')
            ->where('fcb.field_id = ?', $id)
            ->orderBy('fcb.position asc')
            ->execute();
    }

    /**
     * Delete Combobox according to its parent id
     * @param int $id, id of Combobox to delete
     * @return true
     */
    public function setComboboxToNullById($id) {
        Doctrine_Query::create()
            ->update('FieldCombobox fcb')
            ->set('fcb.is_active','?',0)
            ->where('fcb.field_id = ?', $id)
            ->execute();
        return true;
    }


    public function getComboboxItemById($id) {
        return Doctrine_Query::create()
            ->from('FieldCombobox fcb')
            ->select('fcb.*')
            ->where('fcb.id = ?', $id)
            ->execute();
    }

}