<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FieldFileTable extends Doctrine_Table {
    /**
     * 
     * create new instance of FieldRadiogroupTable
     * @return object FieldRadiogroupTable
     */
    public static function instance() {
       return Doctrine::getTable('FieldFile');
    }


    /**
     * update file by id
     *
     * @param int $id, id to update
     * @param array $data, data to update
     * @return true
     */
    public function updateFieldFileById($id, $data) {
        Doctrine_Query::create()
            ->update('FieldFile ff')
            ->set('ff.regex','?',$data['fieldFile_regularexpression'])
            ->where('ff.field_id = ?',$id)
            ->execute();
        return true;
    }


    public function findFileByFieldId($id) {
        return Doctrine_Query::create()
            ->select('ff.*')
            ->from('FieldFile ff')
            ->where('ff.field_id = ?', $id)
            ->execute();    
    }
}