<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FieldCheckboxgroupTable extends Doctrine_Table {

    /**
     * create new instance of FieldCheckboxgroupTable
     * @return object FieldCheckboxgroupTable
     */
    public static function instance() {
       return Doctrine::getTable('FieldCheckboxgroup');
    }


    /**
     * Find all groups for a parent field
     * @param int $id, id of the parent field
     * @return Doctrine_Collection
     */
    public function findCheckboxgroupByFieldId($id) {
        return Doctrine_Query::create()
            ->from('FieldCheckboxgroup fcg')
            ->select('fcg.*')
            ->where('fcg.field_id = ?', $id)
            ->orderBy('fcg.position asc')
            ->execute();
    }


    /**
     * Sets all checkbox to inactive for an field id
     * @param int $id , id of field
     * @return true
     */
    public function setCheckboxgroupToNullById($id) {
        Doctrine_Query::create()
            ->update('FieldCheckboxgroup fcbg')
            ->set('fcbg.isactive','?',0)
            ->where('fcbg.field_id = ?', $id)
            ->execute();
        return true;
    }


    public function getCheckboxgroupItemById($id) {
        return Doctrine_Query::create()
            ->from('FieldCheckboxgroup fcbg')
            ->select('fcbg.*')
            ->where('fcbg.id = ?', $id)
            ->execute();
    }


}