<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FieldNumberTable extends Doctrine_Table {
    /**
     *
     * create new instance of FieldNumber
     * @return object FieldNumber
     */
    public static function instance() {
        return Doctrine::getTable('FieldNumber');
    }

    /**
     * Update number by id
     * @param int $id, id of number
     * @param array $data, data to update
     * @return true
     */
    public function updateFieldNumberById($id, $data) {
        Doctrine_Query::create()
            ->update('FieldNumber fn')
            ->set('fn.defaultvalue','?', $data['fieldNumber_standard'])
            ->set('fn.regex','?',$data['fieldNumber_regularexpression'])
            ->set('fn.comboboxvalue','?',$data['fieldNumber_regularexpressioncombo'])
            ->where('fn.field_id = ?',$id)
            ->execute();
        return true;
    }

    /**
     * Get content of a field by its id
     * @param int $id, id of the field
     * @return Doctrine_Collection
     */
    public function getNumberByFieldId($id) {
        return Doctrine_Query::create()
            ->select('fn.*')
            ->from('FieldNumber fn')
            ->where('fn.field_id = ?', $id)
            ->execute();
    }

}