<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailinglistAllowedSenderTable extends Doctrine_Table {

    /**
     * create new instance of MailinglistAuthorizationSetting
     * @return object MailinglistAuthorizationSetting
     */
    public static function instance() {
        return Doctrine::getTable('MailinglistAllowedSender');
    }


    /**
     * ID of the users
     * @param int $id
     * @return Doctrine_Collection
     */
    public function getAllowedSenderById($id) {
        return Doctrine_Query::create()
               ->select('mlas.*, ul.id, CONCAT(ud.firstname,\' \',ud.lastname) AS name')
               ->from('MailinglistAllowedSender mlas')
               ->leftJoin('mlas.UserLogin ul')
               ->leftJoin('ul.UserData ud')
               ->where('mlas.mailinglist_version_id = ?', $id)
               ->orderBy('mlas.position asc')
               ->groupBy('mlas.id')
               ->execute();
    }


    /**
     * Remove users from allowed sender list
     * @param array $ids, id of users
     * @return true
     */
    public function deleteAllowedUsersByIdInArray(array $ids) {
        Doctrine::getTable('MailinglistAllowedSender')
                ->createQuery('mlas')
                ->whereIn('mlas.id', $ids)
                ->execute()->delete();
        return true;
    }


    public function  getAllowedSenderByMailinglistIdAndUserId($userId, $versionId) {
        return Doctrine_Query::create()
               ->select('mlas.*')
               ->from('MailinglistAllowedSender mlas')
               ->where('mlas.mailinglist_version_id = ?', $versionId)
               ->andWhere('mlas.user_id = ?', $userId)
               ->orderBy('mlas.position asc')
               ->execute();
        
    }

}