<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailinglistAuthorizationSettingTable extends Doctrine_Table {

    /**
     * create new instance of MailinglistAuthorizationSetting
     * @return object MailinglistAuthorizationSetting
     */
    public static function instance() {
        return Doctrine::getTable('MailinglistAuthorizationSetting');
    }


    /**
     * Set all Auth rights to 0
     *
     * @param int $id, id to set 0
     * @return true
     */
    public function setAuthorizationToNullById($id) {
        Doctrine_Query::create()
            ->update('MailinglistAuthorizationSetting mas')
            ->set('mas.delete_workflow','?',0)
            ->set('mas.archive_workflow','?',0)
            ->set('mas.stop_new_workflow','?',0)
            ->set('mas.details_workflow','?',0)
            ->where('mas.mailinglist_template_id = ?', $id)
            ->execute();
        return true;
    }

    
    /**
     * Update table items for AuthorizationConfiguration
     * @param int $id, id of the row to update
     * @param string $column, column of the tablerow which is to update
     * @return true;
     */
    public function updateAuthorizationConfigurationById($id, $value, $column) {
        Doctrine_Query::create()
            ->update('MailinglistAuthorizationSetting mas')
            ->set('mas.'.$column,'?', 1)
            ->where ('mas.mailinglist_version_id = ?',$id)
            ->andWhere('mas.type = ?', $value)
            ->execute();
        return true;
    }

    /**
     * Get auth. settings by id
     * @param int $id
     * @return Doctrine_Collection
     */
    public function getAuthorizationById($id) {
        return Doctrine_Query::create()
            ->from('MailinglistAuthorizationSetting mlas')
            ->where ('mlas.mailinglist_version_id = ?',$id)
            ->execute();

    }


    public function getSettingsByType($name, $mailinglistVersionId) {
        return Doctrine_Query::create()
            ->from('MailinglistAuthorizationSetting mlas')
            ->where ('mlas.type = ?',$name)
            ->andWhere('mlas.mailinglist_version_id = ?', $mailinglistVersionId)
            ->execute();
    }


}