<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserWorkflowConfigurationTable extends Doctrine_Table {
    /**
     *
     * create new instance of UserWorkflowConfigurationTable
     * @return object UserWorkflowConfigurationTable
     */
    public static function instance() {
        return Doctrine::getTable('UserWorkflowConfiguration');
    }

    /**
     * Returns Worklfowconfiguration for a single user
     *
     * @param int $id, id of the user
     * @return Doctrine_Collection
     */
    public function getSingleUserWorkflowConfigurattion($id) {
      return Doctrine_Query::create()
            ->select('uwc.*')
            ->from('UserWorkflowConfiguration uwc')
            ->where('uwc.user_id = ?', $id)
            ->orderBy('uwc.position ASC')
            ->execute();
    }

    /**
     * deletes workflow config for a user
     * @param int $user_id, userid
     * @return true
     */
    public function deleteSingleUserWorkflowConfigurattion($user_id) {
        Doctrine_Query::create()
            ->delete('UserWorkflowConfiguration')
            ->from('UserWorkflowConfiguration uwc')
            ->where('uwc.user_id = ?', $user_id)
            ->execute();
        return true;
    }
}