<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSettingTable extends Doctrine_Table {
    /**
     * create new instance of usersettingtable
     * @return object usersettingtable
     */
    public static function instance() {
        return Doctrine::getTable('UserSetting');
    }

    /**
     * Get usersettings by id
     * @param int $id, id of user
     * @return Doctrine_Collection
     */
    public function getUserSettingById($id) {
        return Doctrine_Query::create()
            ->select('us.*')
            ->from('UserSetting us')
            ->where('us.user_id = ?',$id)
            ->execute();
    }

    /**
     * Update Emailformat and Emailtype of an user
     * @param array $data post data
     * @param int $id, user_id
     * @return true
     */
    public function updateUserEmailformatAndEmailtype($data, $user_id) {
        Doctrine_Query::create()
               ->update('UserSetting us')
               ->set('us.emailformat','?',$data['userFirstTab_emailformat'])
               ->set('us.emailtype','?',$data['userFirstTab_emailtype'])
                ->set('us.language','?',$data['userFirstTab_language'])
               ->where('us.user_id = ?', $user_id)
               ->execute();
        return true;
    }

    /**
     * Function updates user settings
     * @param array $data, POST data
     * @param int $user_id, user_id
     * @return true
     */
    public function updateUserSetting($data, $user_id) {
        Doctrine_Query::create()
           ->update('UserSetting us')
           ->set('us.mark_yellow','?',$data['userFourthTab_markyellow'])
           ->set('us.mark_red','?',$data['userFourthTab_markred'])
           ->set('us.mark_orange','?',$data['userFourthTab_markorange'])
           ->set('us.refresh_time','?',$data['userFourthTab_refreshtime'])
           ->set('us.displayed_item','?',$data['userFourthTab_itemsperpage'])
           ->set('us.circulationdefaultsortcolumn','?',$data['userFourthTab_circulationdefaultsortcolumn'])
           ->set('us.circulationdefaultsortdirection','?',$data['userFourthTab_circulationdefaultsortdirection'])
            ->set('us.theme','?',$data['userFourthTab_theme'])
           ->where('us.user_id = ?', $user_id)
           ->execute();
        return true;
    }

    /**
     * Function updates Durationtype and Durationlength
     * @param array $data, POST data
     * @param int $user_id, user_id
     * @return true
     */
    public function updateUserSettingDurationtypeAndDurationlength($data, $user_id) {
        Doctrine_Query::create()
           ->update('UserSetting us')
           ->set('us.duration_type','?',$data['userSecondTab_durationlength_type'])
           ->set('us.duration_length','?',$data['userSecondTab_durationlength'])
           ->where('us.user_id = ?', $user_id)
           ->execute();
        return true;
    }

    /**
     * Function sets firstlogin flag to 0, -> user is logged in.
     * @param id $user_id, user_id
     * @return true
     */
    public function setFirstLogin($user_id) {
        Doctrine_Query::create()
           ->update('UserSetting us')
           ->set('us.first_login','?',0)
           ->where('us.user_id = ?', $user_id)
           ->execute();
        return true;
    }

    /**
     * Load firstlogin flag
     * @param int $user_id, user_id
     * @return Doctrine_Collection
     */
    public function getFirstLogin($user_id) {
        return Doctrine_Query::create()
            ->select('us.firstlogin')
            ->from('UserSetting us')
            ->where('us.user_id = ?',$user_id)
            ->execute();
    }





    




}