<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserAgentTable extends Doctrine_Table {
    /**
     * 
     * create new instance of UserAgentTable
     * @return object UserAgentTable
     */
    public static function instance() {
        return Doctrine::getTable('UserAgent');
    }


    public function getAllUserAgents($id) {
        return Doctrine_Query::create()
            ->select('ua.*')
            ->from('UserAgent ua')
            ->where('ua.user_id = ?', $id)
            ->execute();
    }

    /**
     * Loads all user agents for a specific userid
     * @param int $id, useragents for user
     * @return Doctrine_Collection
     */
    public function getAllUserAgentForSingleUser($id) {
        return Doctrine_Query::create()
            ->select('ua.*')
            ->from('UserAgent ua')
            ->where('ua.user_id = ?', $id)
            ->leftJoin('ua.UserData ud')
            ->leftJoin('ud.UserLogin ul')
            ->orderBy('ua.position asc')
            ->andWhere('ul.deleted_at IS NULL')
            ->execute();
    }


    public function deleteUserAgentByArray (array $ids) {
        Doctrine::getTable('UserAgent')
                ->createQuery('ua')
                ->whereIn('ua.id', $ids)
                ->execute()
                ->delete();

        return true;
        
    }
}