<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowSlotFieldFileTable extends Doctrine_Table {

    public static function instance() {
        return Doctrine::getTable('WorkflowSlotFieldFile');
    }
    

    public function getAllItemsByWorkflowFieldId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowSlotFieldFile wsff')
            ->select('wsff.*,')
            ->where('wsff.workflow_slot_field_id = ?' ,$id)
            ->execute();
    }


    public function geFileById($id) {
        return Doctrine_Query::create()
            ->from('WorkflowSlotFieldFile wsff')
            ->select('wsff.*,')
            ->where('wsff.id = ?' ,$id)
            ->execute();
    }

}