<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowConfigurationTable extends Doctrine_Table {
    /**
     * create new instance of WorkflowConfigurationTable
     * @return object WorkflowConfigurationTable
     */
    public static function instance() {
        return Doctrine::getTable('WorkflowConfiguration');
    }


    /**
     * Clear WorkflowConfiguration table
     * @return <type>
     */
    public function deleteSettings() {
        Doctrine_Query::create()
            ->delete('WorkflowConfiguration')
            ->from ('WorkflowConfiguration wc')
            ->execute();
        return true;
    }

    /**
     * Load Workflowconfiguration
     * @param string $orderby, orderby if needed
     * @return Doctrine_Collection
     */
    public function getWorkflowConfigurattion() {
        return Doctrine_Query::create()
            ->select('wc.*')
            ->from('WorkflowConfiguration wc')
            ->orderBy('wc.position ASC')
            ->execute();
    }
    


}