<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowSlotFieldTextareaTable extends Doctrine_Table {

    public static function instance() {
        return Doctrine::getTable('WorkflowSlotFieldTextarea');
    }



    public function getAllItemsByWorkflowFieldId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowSlotFieldTextarea wsft')
            ->select('wsft.*,')
            ->where('wsft.workflow_slot_field_id = ?' ,$id)
            ->execute();
    }


    public function updateTextareaByWorkflowFieldId($id, $value) {
        Doctrine_Query::create()
            ->update('WorkflowSlotFieldTextarea wsft')
            ->set('wsft.value','?',$value)
            ->where ('wsft.workflow_slot_field_id = ?',$id)
            ->execute();
    }

    public function updateTextareaById ($id, $value) {
        Doctrine_Query::create()
            ->update('WorkflowSlotFieldTextarea wsft')
            ->set('wsft.value','?',$value)
            ->where ('wsft.id = ?',$id)
            ->execute();
    }

}