<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowProcessTable extends Doctrine_Table {

    /**
     *
     * create new instance of AdditionalText
     * @return object UserLoginTable
     */
    public static function instance() {
        return Doctrine::getTable('WorkflowProcess');
    }


    public function getCurrentStation($version_id) {
        return Doctrine_Query::create()
            ->from('WorkflowProcess wfp')
            ->select('wfp.*')
            ->leftJoin('wfp.WorkflowProcessUser wfpu')
            ->where('wfp.workflow_version_id = ?' ,$version_id)
            ->andWhere('wfpu.decission_state = ?', 'WAITING')
            ->execute();
        
    }

    public function deleteWorkflowProcessById($id) {
        Doctrine_Query::create()
            ->delete('WorkflowProcess')
            ->from('WorkflowProcess wfp')
            ->where('wfp.id = ?', $id)
            ->execute();
        return true;
    }


    public function deleteWorkflowProcessByWorkflowSlotId($slot_id) {
        Doctrine_Query::create()
            ->delete('WorkflowProcess')
            ->from('WorkflowProcess wfp')
            ->where('wfp.workflow_slot_id = ?', $slot_id)
            ->execute();
        return true;
    }


    public function getWorkflowProcessByVersionId($version_id) {
        return Doctrine_Query::create()
            ->from('WorkflowProcess wfp')
            ->where('wfp.workflow_version_id = ?' ,$version_id)
            ->execute();

    }

    public function getWorkflowProcessById($id) {
        return Doctrine_Query::create()
            ->from('WorkflowProcess wfp')
            ->where('wfp.id = ?' ,$id)
            ->execute();
    }

    public function getWorkflowProcessBySlotId($slot_id) {
        return Doctrine_Query::create()
            ->from('WorkflowProcess wfp')
            ->where('wfp.workflow_slot_id = ?' ,$slot_id)
            ->execute();

    }





    public function getAllWaitingStations() {
        return Doctrine_Query::create()
            ->select('wp.*, wpu.user_id, wpu.id')
            ->from('WorkflowProcess wp')
            ->leftJoin('wp.WorkflowProcessUser wpu')
            ->where('wpu.decission_state = ?','WAITING')
            ->orderBy('wpu.user_id ASC')
            ->execute();
    }
    
}