<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowSlotFieldCheckboxgroupTable extends Doctrine_Table {



    public static function instance() {
        return Doctrine::getTable('WorkflowSlotFieldCheckboxgroup');
    }



    public function getAllItemsByWorkflowFieldId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowSlotFieldCheckboxgroup wsfcg')
            ->select('wsfcg.*,')
            ->where('wsfcg.workflow_slot_field_id = ?' ,$id)
            ->orderBy('wsfcg.position ASC')
            ->execute();
    }


    public function updateCheckboxgroupById($id, $value) {
        Doctrine_Query::create()
            ->update('WorkflowSlotFieldCheckboxgroup wsfcg')
            ->set('wsfcg.value','?',$value)
            ->where ('wsfcg.id = ?',$id)
            ->execute();
    }

    public function getCheckboxgroupById($id) {
        return Doctrine_Query::create()
            ->from('WorkflowSlotFieldCheckboxgroup wsfcg')
            ->select('wsfcg.*,')
            ->where('wsfcg.id = ?' ,$id)
            ->orderBy('wsfcg.position ASC')
            ->execute();
    }


    public function setToNullByFieldId($wfsId) {
        Doctrine_Query::create()
            ->update('WorkflowSlotFieldCheckboxgroup wsfcg')
            ->set('wsfcg.value','?', 0)
            ->where ('wsfcg.workflow_slot_field_id = ?',$wfsId)
            ->execute();

    }

}