<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowSlotFieldRadiogroupTable extends Doctrine_Table {


    public static function instance() {
        return Doctrine::getTable('WorkflowSlotFieldRadiogroup');
    }



    public function getAllItemsByWorkflowFieldId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowSlotFieldRadiogroup wsfrg')
            ->select('wsfrg.*,')
            ->where('wsfrg.workflow_slot_field_id = ?' ,$id)
            ->orderBy('wsfrg.position ASC')
            ->execute();
    }



    public function updateRadiogroupById($id, $value) {
        Doctrine_Query::create()
            ->update('WorkflowSlotFieldRadiogroup wsfrg')
            ->set('wsfrg.value','?',$value)
            ->where ('wsfrg.id = ?',$id)
            ->execute();
    }

    public function getRadiogroupById($id) {
      return Doctrine_Query::create()
            ->from('WorkflowSlotFieldRadiogroup wsfrg')
            ->select('wsfrg.*,')
            ->where('wsfrg.id = ?' ,$id)
            ->orderBy('wsfrg.position ASC')
            ->execute();
    }


    public function setToNullByFieldId($wfsId) {
        Doctrine_Query::create()
            ->update('WorkflowSlotFieldRadiogroup wsfrg')
            ->set('wsfrg.value','?', 0)
            ->where ('wsfrg.workflow_slot_field_id = ?',$wfsId)
            ->execute();

    }


}