<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowSlotFieldDateTable extends Doctrine_Table {

    public static function instance() {
        return Doctrine::getTable('WorkflowSlotFieldDate');
    }



    public function getAllItemsByWorkflowFieldId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowSlotFieldDate wsfd')
            ->select('wsfd.*,')
            ->where('wsfd.workflowslotfield_id = ?' ,$id)
            ->execute();
    }



    public function updateDateByWorkflowFieldId($id, $value) {
        Doctrine_Query::create()
            ->update('WorkflowSlotFieldDate wsfd')
            ->set('wsfd.value','?',$value)
            ->where ('wsfd.workflowslotfield_id = ?',$id)
            ->execute();
    }

    public function updateDateById($id, $value) {
     Doctrine_Query::create()
            ->update('WorkflowSlotFieldDate wsfd')
            ->set('wsfd.value','?',$value)
            ->where ('wsfd.id = ?',$id)
            ->execute();
    }

}