<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowProcessUserTable extends Doctrine_Table {


    /**
     *
     * create new instance of AdditionalText
     * @return object UserLoginTable
     */
    public static function instance() {
        return Doctrine::getTable('WorkflowProcessUser');
    }

    
    public function skipStation($id) {
         return Doctrine_Query::create()
                ->update('WorkflowProcessUser wpu')
                ->set('wpu.date_of_decission','?',time())
                ->set('wpu.decission_state', '?', 'SKIPPED')
                ->where('wpu.id = ?', $id)
                ->execute();

    }

    public function skipAllStation($id) {
         return Doctrine_Query::create()
                ->update('WorkflowProcessUser wpu')
                ->set('wpu.date_of_decission','?',time())
                ->set('wpu.decission_state', '?', 'SKIPPED')
                ->where('wpu.workflow_slot_user_id = ?', $id)
                ->execute();

    }

    public function getProcessUserByWorkflowSlotUserId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowProcessUser wpu')
            ->where('wpu.workflow_slot_user_id = ?', $id)
            ->orderBy('wpu.id ASC')
            ->execute();
    }


    public function getProcessById($id) {
        return Doctrine_Query::create()
            ->from('WorkflowProcessUser wpu')
            ->where('wpu.id = ?', $id)
            ->execute();
    }


    public function getProcessAndSubstituteProcessByProcessId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowProcessUser wfpu')
            ->where('wfpu.id = ?', $id)
            ->orWhere('wfpu.is_user_agent_of = ?', $id)
            ->orderBy('wfpu.id ASC')
            ->execute();
    }

    /**
     * Set a Process to useragent set
     *
     * @param int $id, id of the process
     * @return true
     */
    public function setProcessToUseragentSet($id) {
        Doctrine_Query::create()
            ->update('WorkflowProcessUser wpu')
            ->set('wpu.decission_state','?','USERAGENTSET')
            ->set('wpu.date_of_decission','?', time())
            ->where('wpu.id = ?', $id)
            ->execute();
        return true;
        
    }

    public function getWaitingProcess() {
        return Doctrine_Query::create()
            ->from('WorkflowProcessUser wfpu')
            ->leftJoin('wfpu.WorkflowProcess wfp')
            ->where('wfpu.decission_state = ?', 'WAITING')
            ->execute();
    }


    public function getWaitingStationToStopByUser($version_id) {
        return Doctrine_Query::create()
            ->from('WorkflowProcessUser wfpu')
            ->leftJoin('wfpu.WorkflowProcess wfp')
            ->where('wfp.workflow_version_id = ?' ,$version_id)
            ->andWhere('wfpu.decission_state = ?', 'WAITING')
            ->execute();
    }


    public function getWorkflowProcessUserByWorklflowProcessId($wfId) {
        return Doctrine_Query::create()
            ->from('WorkflowProcessUser wfpu')
            ->where('wfpu.workflow_process_id = ?' ,$wfId)
            ->execute();
    }


    public function getWaitingStation($workflow_slot_id, $user_id) {
        return Doctrine_Query::create()
            ->from('WorkflowProcessUser wfpu')
            ->leftJoin('wfpu.WorkflowProcess wfp')
            ->where('wfp.workflow_slot_id = ?', $workflow_slot_id)
            ->andWhere('wfpu.decission_state = ?', 'WAITING')
            ->andWhere('wfpu.user_id = ?',$user_id)
            ->execute();
    }






    public function deleteWorkflowProcessUserByWorkfloSlotUserId($workflow_slot_user_id) {
        Doctrine_Query::create()
            ->delete('WorkflowProcessUser')
            ->from('WorkflowProcessUser wfpu')
            ->where('wfpu.workflow_slot_user_id = ?', $workflow_slot_user_id)
            ->execute();
        return true;
        
    }




    public function getActiveProcessUserForWorkflowSlot($workflow_slot_id, $user_id) {
        return Doctrine_Query::create()
            ->from('WorkflowProcessUser wpu')
            ->leftJoin('wpu.WorkflowProcess wp')
            ->where('wpu.decission_state = ?','WAITING')
            ->andWhere('wpu.user_id = ?', $user_id)
            ->andWhere('wp.workflow_slot_id = ?', $workflow_slot_id)
            ->orderBy('wpu.id ASC')
            ->execute();
    }


    public function getWaitingStationByVersionId($version_id) {
        return Doctrine_Query::create()
            ->select('DISTINCT wfpu.user_id, wfpu.id')
            ->from('WorkflowProcessUser wfpu')
            ->leftJoin('wfpu.WorkflowProcess wfp')
            ->where('wfp.workflow_version_id = ?' ,$version_id)
            ->andWhere('wfpu.decission_state = ?', 'WAITING')
            ->orderBy('wfpu.user_id ASC')
            ->execute();
    }


    public function setProcessToUseragentSetByCronjob($id) {
        Doctrine_Query::create()
            ->update('WorkflowProcessUser wpu')
            ->set('wpu.decission_state','?','USERAGENTSET')
            ->set('wpu.date_of_decission','?', time())
            ->set('wpu.useragentsetbycronjob','?', 1)
            ->where('wpu.id = ?', $id)
            ->execute();
        return true;

    }


    public function setProcessToUseragentSetByCronjobAndByProcessId($processId, $flag) {
        $query = Doctrine_Query::create()
            ->update('WorkflowProcessUser wpu')
            ->set('wpu.decission_state','?','USERAGENTSET')
            ->set('wpu.date_of_decission','?', time())
            ->where('wpu.workflow_process_id = ?', $processId)
            ->andWhere('wpu.useragentsetbycronjob = ?',$flag)
            ->execute();
        return true;
    }
    

}