<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkflowSlotFieldNumberTable extends Doctrine_Table {


    public static function instance() {
        return Doctrine::getTable('WorkflowSlotFieldNumber');
    }



    public function getAllItemsByWorkflowFieldId($id) {
        return Doctrine_Query::create()
            ->from('WorkflowSlotFieldNumber wsfn')
            ->select('wsfn.*,')
            ->where('wsfn.workflowslotfield_id = ?' ,$id)
            ->execute();
    }


    public function updateNumberByWorkflowFieldId($id, $value) {
        Doctrine_Query::create()
            ->update('WorkflowSlotFieldNumber wsfn')
            ->set('wsfn.value','?',$value)
            ->where ('wsfn.workflowslotfield_id = ?',$id)
            ->execute();
    }


    public function updateNumberById($id, $value) {
        Doctrine_Query::create()
            ->update('WorkflowSlotFieldNumber wsfn')
            ->set('wsfn.value','?',$value)
            ->where ('wsfn.id = ?',$id)
            ->execute();
    }







}