<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version56 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('cf_credential', 'usermodule');
        $this->removeColumn('cf_credential', 'usergroup');
        $this->removeColumn('cf_credential', 'userright');
        $this->removeColumn('cf_credential', 'usermoduleposition');
        $this->removeColumn('cf_credential', 'usergroupposition');
        $this->addColumn('cf_credential', 'user_module', 'string', '255', array(
             ));
        $this->addColumn('cf_credential', 'user_group', 'string', '255', array(
             ));
        $this->addColumn('cf_credential', 'user_right', 'string', '255', array(
             ));
        $this->addColumn('cf_credential', 'user_module_position', 'integer', '3', array(
             ));
        $this->addColumn('cf_credential', 'user_group_position', 'integer', '3', array(
             ));
        $this->changeColumn('cf_role', 'id', 'integer', '8', array(
             'autoincrement' => '1',
             'primary' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('cf_credential', 'usermodule', 'string', '255', array(
             ));
        $this->addColumn('cf_credential', 'usergroup', 'string', '255', array(
             ));
        $this->addColumn('cf_credential', 'userright', 'string', '255', array(
             ));
        $this->addColumn('cf_credential', 'usermoduleposition', 'integer', '3', array(
             ));
        $this->addColumn('cf_credential', 'usergroupposition', 'integer', '3', array(
             ));
        $this->removeColumn('cf_credential', 'user_module');
        $this->removeColumn('cf_credential', 'user_group');
        $this->removeColumn('cf_credential', 'user_right');
        $this->removeColumn('cf_credential', 'user_module_position');
        $this->removeColumn('cf_credential', 'user_group_position');
    }
}