<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfmailinglistversion extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_mailinglistversion', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'mailinglisttemplate_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'documenttemplateversion_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'sendtoallslotsatonce' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'version' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'activeversion' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_mailinglistversion');
    }
}