<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfworkflowtemplate extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_workflowtemplate', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'mailinglisttemplateversion_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'documenttemplateversion_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'sender_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'isstopped' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'stopped_at' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'stopped_by' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'completed_at' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'iscompleted' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'isarchived' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'archived_at' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'archived_by' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'endaction' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_workflowtemplate');
    }
}