<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfauthenticationconfiguration extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_authenticationconfiguration', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'authenticationtype' => 
             array(
              'type' => 'string',
              'length' => 20,
             ),
             'ldaphost' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldapdomain' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldapbindusernameandcontext' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldappassword' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldaprootcontext' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldapusersearchattribute' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldapfirstname' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldaplastname' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldapusername' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldapemail' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldapoffice' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldapphone' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldapcontext' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'ldapadduser' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'openidserver' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'firstlogin' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'allowdirectlogin' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_authenticationconfiguration');
    }
}