<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfworkflowprocess extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_workflowprocess', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'workflowtemplate_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'workflowversion_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'workflowslot_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_workflowprocess');
    }
}