<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfworkflowconfiguration extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_workflowconfiguration', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'columntext' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'isactive' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_workflowconfiguration');
    }
}