<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfusersetting extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_usersetting', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
             ),
             'language' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'markyellow' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'markred' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'markorange' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'refreshtime' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'default' => 180,
             ),
             'displayeditem' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'default' => 25,
             ),
             'durationtype' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'durationlength' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'emailformat' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'emailtype' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'circulationdefaultsortcolumn' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'circulationdefaultsortdirection' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'theme' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'firstlogin' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_usersetting');
    }
}