<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfuserlogin extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_userlogin', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'role_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'username' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'password' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_userlogin');
    }
}