<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfuserconfiguration extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_userconfiguration', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'role_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'durationtype' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'durationlength' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'displayeditem' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'refreshtime' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'markyellow' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'markred' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'markorange' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'password' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'language' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'emailformat' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'emailtype' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'theme' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'circulationdefaultsortcolumn' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'circulationdefaultsortdirection' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_userconfiguration');
    }
}