<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcffield extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_field', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'writeprotected' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'color' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_field');
    }
}