<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfworkflowprocessuser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_workflowprocessuser', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'workflowprocess_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'workflowslotuser_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'inprogresssince' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'decissionstate' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'dateofdecission' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'isuseragentof' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'useragentsetbycronjob' => 
             array(
              'type' => 'integer',
              'length' => 3,
              'default' => 0,
             ),
             'resendet' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_workflowprocessuser');
    }
}