<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfmailinglisttemplate extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_mailinglisttemplate', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'documenttemplatetemplate_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'isactive' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_mailinglisttemplate');
    }
}