<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version60 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('cf_userlogin', 'cf_userlogin_role_id_cf_role_id');
        $this->createForeignKey('cf_user_login', 'cf_user_login_role_id_cf_role_id', array(
             'name' => 'cf_user_login_role_id_cf_role_id',
             'local' => 'role_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_role',
             ));
        $this->addIndex('cf_user_login', 'cf_user_login_role_id', array(
             'fields' => 
             array(
              0 => 'role_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('cf_userlogin', 'cf_userlogin_role_id_cf_role_id', array(
             'name' => 'cf_userlogin_role_id_cf_role_id',
             'local' => 'role_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_role',
             ));
        $this->dropForeignKey('cf_user_login', 'cf_user_login_role_id_cf_role_id');
        $this->removeIndex('cf_user_login', 'cf_user_login_role_id', array(
             'fields' => 
             array(
              0 => 'role_id',
             ),
             ));
    }
}