<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfworkflowversion extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_workflowversion', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'workflowtemplate_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'additionaltext_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'activeversion' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'version' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'endreason' => 
             array(
              'type' => 'string',
              'length' => 1000,
             ),
             'content' => 
             array(
              'type' => 'string',
              'length' => 5000,
             ),
             'contenttype' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'startworkflow_at' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'workflowisstarted' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_workflowversion');
    }
}