<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version59 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('cf_userworkflowconfiguration', 'columntext');
        $this->removeColumn('cf_userworkflowconfiguration', 'isactive');
        $this->addColumn('cf_user_workflow_configuration', 'column_text', 'string', '255', array(
             ));
        $this->addColumn('cf_user_workflow_configuration', 'is_active', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->addColumn('cf_userworkflowconfiguration', 'columntext', 'string', '255', array(
             ));
        $this->addColumn('cf_userworkflowconfiguration', 'isactive', 'string', '255', array(
             ));
        $this->removeColumn('cf_user_workflow_configuration', 'column_text');
        $this->removeColumn('cf_user_workflow_configuration', 'is_active');
    }
}