<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('cf_credentialrole', 'cf_credentialrole_credential_id_cf_credential_id', array(
             'name' => 'cf_credentialrole_credential_id_cf_credential_id',
             'local' => 'credential_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_credential',
             ));
        $this->createForeignKey('cf_fieldcheckbox', 'cf_fieldcheckbox_field_id_cf_field_id', array(
             'name' => 'cf_fieldcheckbox_field_id_cf_field_id',
             'local' => 'field_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_field',
             ));
        $this->createForeignKey('cf_fieldcheckboxgroup', 'cf_fieldcheckboxgroup_field_id_cf_field_id', array(
             'name' => 'cf_fieldcheckboxgroup_field_id_cf_field_id',
             'local' => 'field_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_field',
             ));
        $this->createForeignKey('cf_fieldcombobox', 'cf_fieldcombobox_field_id_cf_field_id', array(
             'name' => 'cf_fieldcombobox_field_id_cf_field_id',
             'local' => 'field_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_field',
             ));
        $this->createForeignKey('cf_fielddate', 'cf_fielddate_field_id_cf_field_id', array(
             'name' => 'cf_fielddate_field_id_cf_field_id',
             'local' => 'field_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_field',
             ));
        $this->createForeignKey('cf_fieldfile', 'cf_fieldfile_field_id_cf_field_id', array(
             'name' => 'cf_fieldfile_field_id_cf_field_id',
             'local' => 'field_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_field',
             ));
        $this->createForeignKey('cf_fieldnumber', 'cf_fieldnumber_field_id_cf_field_id', array(
             'name' => 'cf_fieldnumber_field_id_cf_field_id',
             'local' => 'field_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_field',
             ));
        $this->createForeignKey('cf_fieldradiogroup', 'cf_fieldradiogroup_field_id_cf_field_id', array(
             'name' => 'cf_fieldradiogroup_field_id_cf_field_id',
             'local' => 'field_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_field',
             ));
        $this->createForeignKey('cf_fieldtextarea', 'cf_fieldtextarea_field_id_cf_field_id', array(
             'name' => 'cf_fieldtextarea_field_id_cf_field_id',
             'local' => 'field_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_field',
             ));
        $this->createForeignKey('cf_fieldtextfield', 'cf_fieldtextfield_field_id_cf_field_id', array(
             'name' => 'cf_fieldtextfield_field_id_cf_field_id',
             'local' => 'field_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_field',
             ));
        $this->createForeignKey('cf_userconfiguration', 'cf_userconfiguration_role_id_cf_role_id', array(
             'name' => 'cf_userconfiguration_role_id_cf_role_id',
             'local' => 'role_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_role',
             ));
        $this->createForeignKey('cf_userlogin', 'cf_userlogin_role_id_cf_role_id', array(
             'name' => 'cf_userlogin_role_id_cf_role_id',
             'local' => 'role_id',
             'foreign' => 'id',
             'foreignTable' => 'cf_role',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('cf_credentialrole', 'cf_credentialrole_credential_id_cf_credential_id');
        $this->dropForeignKey('cf_fieldcheckbox', 'cf_fieldcheckbox_field_id_cf_field_id');
        $this->dropForeignKey('cf_fieldcheckboxgroup', 'cf_fieldcheckboxgroup_field_id_cf_field_id');
        $this->dropForeignKey('cf_fieldcombobox', 'cf_fieldcombobox_field_id_cf_field_id');
        $this->dropForeignKey('cf_fielddate', 'cf_fielddate_field_id_cf_field_id');
        $this->dropForeignKey('cf_fieldfile', 'cf_fieldfile_field_id_cf_field_id');
        $this->dropForeignKey('cf_fieldnumber', 'cf_fieldnumber_field_id_cf_field_id');
        $this->dropForeignKey('cf_fieldradiogroup', 'cf_fieldradiogroup_field_id_cf_field_id');
        $this->dropForeignKey('cf_fieldtextarea', 'cf_fieldtextarea_field_id_cf_field_id');
        $this->dropForeignKey('cf_fieldtextfield', 'cf_fieldtextfield_field_id_cf_field_id');
        $this->dropForeignKey('cf_userconfiguration', 'cf_userconfiguration_role_id_cf_role_id');
        $this->dropForeignKey('cf_userlogin', 'cf_userlogin_role_id_cf_role_id');
    }
}