<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfworkflowslot extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_workflowslot', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'workflowversion_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'slot_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => 3,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_workflowslot');
    }
}