<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcfworkflowversionattachment extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cf_workflowversionattachment', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 20,
              'primary' => true,
              'autoincrement' => true,
             ),
             'workflowtemplate_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'workflowversion_id' => 
             array(
              'type' => 'integer',
              'length' => 20,
             ),
             'filename' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'hashname' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('cf_workflowversionattachment');
    }
}